export const bookCategories = [
  { value: 'fiction', label: 'Художня' },
  { value: 'nonfiction', label: 'Документальна' },
  { value: 'fantasy', label: 'Фентезі' },
  { value: 'sci-fi', label: 'Наукова фантастика' },
  { value: 'detective', label: 'Детектив' },
  { value: 'romance', label: 'Романтика' },
  { value: 'thriller', label: 'Трилер' },
  { value: 'history', label: 'Історична' },
  { value: 'biography', label: 'Біографія' },
  { value: 'selfhelp', label: 'Саморозвиток' },
  { value: 'psychology', label: 'Психологія' },
  { value: 'philosophy', label: 'Філософія' },
  { value: 'poetry', label: 'Поезія' },
  { value: 'children', label: 'Дитяча' },
  { value: 'young-adult', label: 'Підліткова ' },
  { value: 'science', label: 'Наукова' },
  { value: 'religion', label: 'Релігія' },
  { value: 'classic', label: 'Класика' },
  { value: 'horror', label: 'Жахи' },
  { value: 'adventure', label: 'Пригоди' },
  { value: 'drama', label: 'Драма' },
  { value: 'humor', label: 'Гумор / Сатира' },
  { value: 'art', label: 'Мистецтво / Фото' },
  { value: 'travel', label: 'Подорожі' },
  { value: 'cookbook', label: 'Кулінарія' },
  { value: 'business', label: 'Бізнес' },
  { value: 'technology', label: 'Технології / ІТ' },
  { value: 'guide', label: 'Довідники' },
  { value: 'education', label: 'Освіта' },
  { value: 'health', label: 'Медицина' },
  { value: 'language', label: 'Вивчення мов' },
  { value: 'politics', label: 'Політика' },
  { value: 'other', label: 'Інше' },
];

export const findCategoryLabel = (value: string) => {
  return bookCategories.find((el) => el.value === value)?.label;
};
